### ISSUE TITLE
Occasionally weird errors like 'Unable to determine array type, found unknown header byte 0xc4 at reader offset 59'

### ISSUE THREAD

**Issue by berndruecker** [camunda-cloud/zeebe-process-test#110]
## Description
I am currently playing with spring-zeebe to support testing in spring environments based on zeebe-process-test 1.3.0-alpha3. I occasionally get the below exception on an assertion of process completion `assertThat(processInstance).isCompleted()`. Could it have to do with multi-threading, that some thread is still executing jobs and I do an assertion at the same time?

```
java.lang.RuntimeException: Could not deserialize object [JobBatchRecord]. Deserialization stuck at offset 60 of length 201

	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:38)
	at io.camunda.zeebe.logstreams.impl.log.LoggedEventImpl.readValue(LoggedEventImpl.java:135)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.mapToRecord(RecordStreamSourceImpl.java:169)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.updateWithNewRecords(RecordStreamSourceImpl.java:148)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.records(RecordStreamSourceImpl.java:46)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.recordsOfValueType(RecordStreamSourceImpl.java:53)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.processInstanceRecords(RecordStreamSourceImpl.java:60)
	at io.camunda.zeebe.process.test.filters.StreamFilter.processInstance(StreamFilter.java:9)
	at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssert.isProcessInstanceCompleted(ProcessInstanceAssert.java:106)
	at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssert.isCompleted(ProcessInstanceAssert.java:82)
	at io.berndruecker.playground.zeebe.tests.SimpleSpringBootTest.lambda$waitForCompletion$0(SimpleSpringBootTest.java:77)
	at org.testcontainers.shaded.org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:234)
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:221)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Could not read property 'variables'
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:112)
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:32)
	... 17 more
Caused by: io.camunda.zeebe.msgpack.spec.MsgpackReaderException: Unable to determine array type, found unknown header byte 0xc4 at reader offset 59
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.exceptionOnUnknownHeader(MsgPackReader.java:474)
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.readArrayHeader(MsgPackReader.java:107)
	at io.camunda.zeebe.msgpack.value.ArrayValue.read(ArrayValue.java:94)
	at io.camunda.zeebe.msgpack.property.BaseProperty.read(BaseProperty.java:75)
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:110)
	... 18 more
```

@remcowesterhoud maybe?

**Comment by remcowesterhoud** [comment]
I don't have clear answer on what causes this. I don't think it has to do with multi-threading. What's happening is that it is trying to read the log stream, but it encounters an event on there that it cannot map to a record (a `JobBatchRecord` to be precise).

@pihme Do you have an idea what could be the cause of this?

**Comment by pihme** [comment]
Not really. But I would pursue the multi-threading lead a little further. More often than not, in the past, it has been a multi-threading issue. These things are difficult to debug. 

Let me elaborate on why behavior like this can be caused by multi threading. We have essentially an in memory commit log. The memory will be shared by multiple threads. Write operations are not atomic, and read and write operations are not necessarily synchronized.

So something that happened in the past was that we were reading from the event log while at the same time it was being written to. At this point you read garbage, pretty much, and exceptions like the above can happen.

It may also not be the commit log per se, which is accessed concurrently. It might also be a byte buffer that is used temporarily to read/write something.

**Comment by pihme** [comment]
Note also that the Agrona library we use is heavily relying on shared byte buffers. Like all these wrap calls (e.g. `valueBufferView.wrap(valueBuffer, 0, value.getLength());`) - they don't copy the buffer, they wrap around it. So if two objects wrap around the same buffer and one tries to read and one tries to write, we have concurrent access.

I guess we never saw it, because we tested it with single threads. And now Bernd is using multiple threads and stumbles into it.

**Comment by pihme** [comment]
I think I have a suspect. I think `RecordStreamSourceImpl` is not thread safe. If we call `updateWithNewRecords` from multiple threads we mess up the `logStreamReader`. This reader is not ours. It is from Zeebe, which assumes we run as single threaded actors. (by and large)

So if one thread calls `next()` you will get a `LoggedEvent`. This is not a unique object, but a pointer to a field inside `LogStreamReaderImpl`. Now you use this event to map it to a record.

At the same time, another threads calls `next()` also, which does that:
```java
        if (!this.hasNext()) {
            throw new NoSuchElementException();
        } else {
            this.currentEventBuffer.wrap(this.nextEventBuffer, this.nextEvent.getFragmentOffset(), this.nextEvent.getFragmentLength());
            this.nextEventOffset += this.nextEvent.getLength();
            this.nextEvent.wrap(this.nextEventBuffer, this.nextEventOffset);
            return this.currentEvent;
        }
```
So it modifies the buffer that is inside the `LoggedEvent` that the other thread is currently reading from.

This maybe isn't the only problem we have, but it is definitely one of them.

So synchronized on all methods that interact with the log stream reader would be a first step.

**Comment by berndruecker** [comment]
Sounds reasonable to me - thanks a lot for looking into it so quickly. Just to be sure: By "synchronize all methods" you refer to methods within the "zeebe-process-test" module - right? Or you mean my code?

**Comment by pihme** [comment]
Yes, I meant code in "zeebe-process-test". Most of it is guarded by an actor scheduler or single threaded executor already, but as you discovered, we have more work to do here.

**Comment by berndruecker** [comment]
Yeah - thx. I'll give it a try asap 👍

**Comment by berndruecker** [comment]
Looks like SNAPSHOT is still not pushed to maven central - so I can't easily try it out :-( Created https://github.com/camunda-cloud/zeebe-process-test/issues/118
