### ISSUE TITLE
Can't build test library locally

### ISSUE THREAD

**Issue by berndruecker** [camunda-cloud/zeebe-process-test#119]
When checking out the current head on master I can't build the library as there are test failures.

```
ERROR] Failures:
[ERROR]   MessageAssertTest$HappyPathTests.testHasExpired:108 Message with key 2251799813685251 has not expired
[ERROR]   MessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure:274
Expecting code to raise a throwable.
[ERROR]   ProcessInstanceAssertTest$UnhappyPathTests.testProcessInstanceHasPassedElementsInOrderFailure:698
Expecting message to be:
  "[Ordered elements]
expected: ["endevent", "servicetask", "startevent"]
 but was: ["startevent", "servicetask", "endevent"]"
but was:
  "[Ordered elements]
expected: ["endevent", "servicetask", "startevent"]
 but was: ["startevent", "servicetask", "endevent"]"

Throwable that failed the check:

org.opentest4j.AssertionFailedError: [Ordered elements]
expected: ["endevent", "servicetask", "startevent"]
 but was: ["startevent", "servicetask", "endevent"]
        at jdk.internal.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssert.hasPassedElementInOrder(ProcessInstanceAssert.java:223)
        at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssertTest$UnhappyPathTests.lambda$testProcessInstanceHasPassedElementsInOrderFailure$8(ProcessInstanceAssertTest.java:693)
        at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssertTest$UnhappyPathTests.testProcessInstanceHasPassedElementsInOrderFailure(ProcessInstanceAssertTest.java:690)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)

[ERROR]   ProcessEventInspectionsTest.testFindFirstProcessInstance:40
Expecting Optional to contain a value but it was empty.
[ERROR]   ProcessEventInspectionsTest.testFindLastProcessInstance:60
Expecting Optional to contain a value but it was empty.
[INFO]
[ERROR] Tests run: 185, Failures: 5, Errors: 0, Skipped: 0
```

**Comment by berndruecker** [comment]
I can build the library with `-DskipTests=true` though

**Comment by pihme** [comment]
Seems to be an issue of flaky tests :-(

On my machine: 
* running it in IDEA runs smoothly even if using "repeat until failure"
* running it from command line I get a test error in 50% of the time; but not always the same one.

Could you maybe do the following?
- note down the Java version and JVM you are using
- run it several times and report whether it is always the same test failing, or different tests

**Comment by berndruecker** [comment]
I run it via Maven command line on this Java version:
```
C:\DEV\Camunda\zeebe-process-test>java --version
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

I can check if multiple runs trigger the same problems reliably

**Comment by pihme** [comment]
If you want, you could also check out branch `stability-improvements`. With this branch I have no longer flaky tests on my machine (but given the nature of flaky tests that doesn't say much).

Will now look into #122 before #120

**Comment by berndruecker** [comment]
Same issue on that branch:

```
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.042 s - in io.camunda.zeebe.process.test.testengine.EngineClientTest
11:57:45.524 [-zb-fs-workers-1] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
11:57:45.524 [-zb-actors-4] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   MessageAssertTest$UnhappyPathTests.testHasNotExpiredFailure:274
Expecting code to raise a throwable.
[ERROR]   ProcessInstanceAssertTest$UnhappyPathTests.testProcessInstanceHasPassedElementsInOrderFailure:698
Expecting message to be:
  "[Ordered elements]
expected: ["endevent", "servicetask", "startevent"]
 but was: ["startevent", "servicetask", "endevent"]"
but was:
  "[Ordered elements]
expected: ["endevent", "servicetask", "startevent"]
 but was: ["startevent", "servicetask", "endevent"]"

Throwable that failed the check:

org.opentest4j.AssertionFailedError: [Ordered elements]
expected: ["endevent", "servicetask", "startevent"]
 but was: ["startevent", "servicetask", "endevent"]
```

**Comment by pihme** [comment]
Hmm, are you maybe on Windows? Could this be a line ending thing?

Because if I look at the readable characters I see no difference. 

This test is comparing the failure messages:
```
          .hasMessage(
              "[Ordered elements] \n"
                  + "expected: [\"endevent\", \"servicetask\", \"startevent\"]\n"
                  + " but was: [\"startevent\", \"servicetask\", \"endevent\"]");
```

It is also the only test which has `\n` in it.

**Comment by berndruecker** [comment]
I am on windows - and yes, I think that is a reasonable possibility :-)

**Comment by pihme** [comment]
You can try again with that branch. I hope it works now on Windows. However, I think there are other issues as well. I saw some errors from `MessageAssertTest` in your log excerpt as well.

Could you maybe run maven with `--fail-never` and share the full log so we can get a broader picture?

**Comment by berndruecker** [comment]
Sure - I'll send you the log file via email
