### ISSUE TITLE
Could not deserialize object [JobBatchRecord]. Deserialization stuck at offset 60 of length 206

### ISSUE THREAD

**Issue by berndruecker** [camunda-cloud/zeebe-process-test#120]
I still have issues with the latest snapshot when using multi-threading, so https://github.com/camunda-cloud/zeebe-process-test/issues/110 seems not to have fixed it all. See exception below.

This exception is now visible EVERY time I run a test case.

```
java.lang.RuntimeException: Could not deserialize object [JobBatchRecord]. Deserialization stuck at offset 60 of length 206

	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:38)
	at io.camunda.zeebe.logstreams.impl.log.LoggedEventImpl.readValue(LoggedEventImpl.java:135)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.mapToRecord(RecordStreamSourceImpl.java:169)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.updateWithNewRecords(RecordStreamSourceImpl.java:148)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.records(RecordStreamSourceImpl.java:46)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.recordsOfValueType(RecordStreamSourceImpl.java:53)
	at io.camunda.zeebe.process.test.testengine.RecordStreamSourceImpl.processInstanceRecords(RecordStreamSourceImpl.java:60)
	at io.camunda.zeebe.process.test.filters.StreamFilter.processInstance(StreamFilter.java:9)
	at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssert.isProcessInstanceCompleted(ProcessInstanceAssert.java:106)
	at io.camunda.zeebe.process.test.assertions.ProcessInstanceAssert.isCompleted(ProcessInstanceAssert.java:82)
	at io.berndruecker.playground.zeebe.tests.SimpleSpringBootTest.lambda$waitForCompletion$0(SimpleSpringBootTest.java:63)
	at org.testcontainers.shaded.org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:234)
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:221)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Could not read property 'variables'
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:112)
	at io.camunda.zeebe.msgpack.UnpackedObject.wrap(UnpackedObject.java:32)
	... 17 more
Caused by: io.camunda.zeebe.msgpack.spec.MsgpackReaderException: Unable to determine array type, found unknown header byte 0xc4 at reader offset 59
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.exceptionOnUnknownHeader(MsgPackReader.java:474)
	at io.camunda.zeebe.msgpack.spec.MsgPackReader.readArrayHeader(MsgPackReader.java:107)
	at io.camunda.zeebe.msgpack.value.ArrayValue.read(ArrayValue.java:94)
	at io.camunda.zeebe.msgpack.property.BaseProperty.read(BaseProperty.java:75)
	at io.camunda.zeebe.msgpack.value.ObjectValue.read(ObjectValue.java:110)
	... 18 more


Process finished with exit code -1

```

**Comment by remcowesterhoud** [comment]
I'm closing this one as it is a duplicate from #158
