### ISSUE TITLE
Sending messages sometimes results in a ClientStatusException

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/zeebe-process-test#98]
**Description**

Now that we fail builds on flaky tests, periodically the build will fail on tests where we send a message using the `ZeebeClient`.
Sending the message will result in a timeout.

```
io.camunda.zeebe.client.api.command.ClientStatusException: deadline exceeded after 9.999761982s. [closed=[], open=[[remote_addr=0.0.0.0/0:0:0:0:0:0:0:1:1123]]]
	at io.camunda.zeebe.bpmnassert.assertions.ProcessInstanceAssertTest$HappyPathTests.testHasCorrelatedMessageByCorrelationKey(ProcessInstanceAssertTest.java:403)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9.999761982s. [closed=[], open=[[remote_addr=0.0.0.0/0:0:0:0:0:0:0:1:1123]]]
	at io.camunda.zeebe.bpmnassert.assertions.ProcessInstanceAssertTest$HappyPathTests.testHasCorrelatedMessageByCorrelationKey(ProcessInstanceAssertTest.java:403)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 9.999761982s. [closed=[], open=[[remote_addr=0.0.0.0/0:0:0:0:0:0:0:1:1123]]]
```

**Comment by remcowesterhoud** [comment]
I have not seen this issue in about a week. I've tried running the tests that were failing before thousands of times, without any failure. I'm not sure why this occurred, or why it stopped. But for now everything seems fine.
I'll close this issue, it can be reopened if the problem comes back.

**Comment by remcowesterhoud** [comment]
Problem occurred again: https://github.com/camunda-cloud/zeebe-process-test/runs/4593881365
